"""
Install a git post-commit hook in every enabled repo listed in config.json.

The hook runs `python -m graph --repo <name>` after each commit, regenerating
only the graph entries for that repo.

Usage:
    python install_hooks.py              # uses config.json next to this script
    python install_hooks.py --config /path/to/config.json
    python install_hooks.py --dry-run   # show what would be written, don't write
"""

import argparse
import json
import os
import stat
import sys
from pathlib import Path

HOOK_TEMPLATE = """\
#!/bin/sh
# Auto-generated by repo-graph/install_hooks.py — do not edit by hand.
# Re-run install_hooks.py to regenerate.
cd "{repo_graph_path}" && python -m graph --repo {repo_name}
"""


def load_config(config_path: Path) -> dict:
    with open(config_path) as f:
        return json.load(f)


def make_executable(path: Path) -> None:
    current = path.stat().st_mode
    path.chmod(current | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def install_hook(repo: dict, repo_graph_path: Path, dry_run: bool) -> bool:
    repo_path = Path(repo["path"])
    hook_dir = repo_path / ".git" / "hooks"
    hook_file = hook_dir / "post-commit"
    content = HOOK_TEMPLATE.format(
        repo_graph_path=repo_graph_path.as_posix(),
        repo_name=repo["name"],
    )

    if not repo_path.exists():
        print(f"  [SKIP   ] {repo['name']} — repo path not found: {repo_path}")
        return False

    if not hook_dir.exists():
        print(f"  [SKIP   ] {repo['name']} — not a git repo (no .git/hooks/): {repo_path}")
        return False

    if dry_run:
        print(f"  [DRY-RUN] {repo['name']} -> {hook_file}")
        print(f"            content: cd {repo_graph_path.as_posix()} && python -m graph --repo {repo['name']}")
        return True

    with open(hook_file, "w", newline="\n") as f:
        f.write(content)
    make_executable(hook_file)
    print(f"  [OK     ] {repo['name']} -> {hook_file}")
    return True


def main(argv=None) -> None:
    parser = argparse.ArgumentParser(description="Install post-commit hooks for all repos in config.json.")
    parser.add_argument("--config", metavar="PATH",
                        help="Path to config.json (default: config.json next to this script)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Show what would be written without writing anything")
    args = parser.parse_args(argv)

    script_dir = Path(__file__).resolve().parent
    config_path = Path(args.config) if args.config else script_dir / "config.json"

    if not config_path.exists():
        print(f"ERROR: config not found: {config_path}", file=sys.stderr)
        sys.exit(1)

    config = load_config(config_path)
    repos = [r for r in config.get("repos", []) if r.get("enabled", True)]

    if not repos:
        print("No enabled repos found in config.json.")
        return

    print(f"Installing post-commit hooks for {len(repos)} repo(s):")
    ok = sum(install_hook(r, script_dir, args.dry_run) for r in repos)
    print(f"\n{'Would install' if args.dry_run else 'Installed'} {ok}/{len(repos)} hooks.")


if __name__ == "__main__":
    main()
